import requests
import time
import os
import sys
from datetime import datetime

sys.path.append(os.path.dirname(os.path.abspath(__file__)))
from opero_runner import analyze_issue


MY_PROJECT_ID = "gitlab-ai-hackathon%2Fparticipants%2F6273024"
MY_TOKEN = "glpat-1oB42kUUpwfr8KM9NpQim286MQp1OjNxZ2FvCw.01.121g3pdrs"


GITHUB_REPO = "facebook/create-react-app"
SEEN_RUN_IDS = set()

def get_failed_runs():
    url = f"https://api.github.com/repos/{GITHUB_REPO}/actions/runs"
    headers = {"Accept": "application/vnd.github+json"}
    params = {"status": "failure", "per_page": 5}
    response = requests.get(url, headers=headers, params=params)
    if response.status_code == 200:
        return response.json().get("workflow_runs", [])
    else:
        print(f"GitHub API error: {response.status_code}")
        return []

def get_job_logs(run_id):
    try:
        url = f"https://api.github.com/repos/{GITHUB_REPO}/actions/runs/{run_id}/jobs"
        headers = {"Accept": "application/vnd.github+json"}
        response = requests.get(url, headers=headers, timeout=20)
        if response.status_code == 200:
            jobs = response.json().get("jobs", [])
            failed = [j for j in jobs if j["conclusion"] == "failure"]
            if failed:
                job = failed[0]
                steps_failed = [s["name"] for s in job.get("steps", []) if s.get("conclusion") == "failure"]
                return f"Job '{job['name']}' failed at steps: {', '.join(steps_failed)}"
    except Exception as e:
        print(f"  Could not fetch logs: {e}")
    return ""

def create_gitlab_issue(title, description):
    url = f"https://gitlab.com/api/v4/projects/{MY_PROJECT_ID}/issues"
    headers = {"PRIVATE-TOKEN": MY_TOKEN}
    data = {
        "title": title,
        "description": description,
        "labels": "incident,opero-auto,github-react"
    }
    response = requests.post(url, headers=headers, data=data)
    print(f"GitLab issue created: {response.status_code}")

def generate_rca(run, result, log):
    url = f"https://gitlab.com/api/v4/projects/{MY_PROJECT_ID}/wikis"
    headers = {"PRIVATE-TOKEN": MY_TOKEN}
    content = f"""# RCA — {datetime.now().strftime('%Y-%m-%d %H:%M')}

## Incident Source
- **Project:** {GITHUB_REPO}
- **Workflow:** {run['name']}
- **Branch:** {run['head_branch']}
- **Failed at:** {run['updated_at']}
- **GitHub URL:** {run['html_url']}

## OPERO Analysis
- **Failure type:** {result['failure']}
- **Severity:** {result['severity']}

## Log Details
{log}

## Resolution Steps
{chr(10).join(f'- {step}' for step in result['fix'])}

> Auto-generated by OPERO — monitoring {GITHUB_REPO}
"""
    data = {
        "title": f"RCA-react-{run['id']}-{int(time.time())}",
        "content": content,
        
    }
    response = requests.post(url, headers=headers, json=data)
    print(f"RCA wiki created: {response.status_code} - {response.text}") #debug

def process_run(run):
    run_id = run["id"]
    if run_id in SEEN_RUN_IDS:
        return
    SEEN_RUN_IDS.add(run_id)

    print(f"\n{'='*50}")
    print(f"Failed workflow detected!")
    print(f"  Repo    : {GITHUB_REPO}")
    print(f"  Workflow: {run['name']}")
    print(f"  Branch  : {run['head_branch']}")
    print(f"  Failed  : {run['updated_at']}")
    print(f"  URL     : {run['html_url']}")

    log = get_job_logs(run_id)
    analyze_text = log if log else run["name"]
    result = analyze_issue(analyze_text)

    print(f"\n  OPERO Analysis:")
    print(f"  Failure : {result['failure']}")
    print(f"  Severity: {result['severity']}")
    print(f"  Fix     : {result['fix'][0]}")

    description = f"""
## OPERO Real-Time Incident

**Source:** {GITHUB_REPO} (GitHub)
**Workflow:** {run['name']}
**Branch:** {run['head_branch']}
**Failed at:** {run['updated_at']}
**URL:** {run['html_url']}

## OPERO Analysis
- **Failure type:** {result['failure']}
- **Severity:** {result['severity']}
- **Suggested fix:** {result['fix'][0]}

## Log Details
{log}

> Auto-triaged by OPERO
"""
    create_gitlab_issue(
        f"OPERO: {result['failure']} in {GITHUB_REPO} — {run['name']}",
        description
    )
    generate_rca(run, result, log)

def watch():
    print(f"OPERO watching {GITHUB_REPO} for real CI failures...")
    print("Checking every 60 seconds\n")
    while True:
        try:
            print(f"[{datetime.now().strftime('%H:%M:%S')}] Checking GitHub Actions...")
            runs = get_failed_runs()
            if runs:
                for run in runs:
                    try:
                        process_run(run)
                    except Exception as e:
                        print(f"  Error processing run: {e}")
            else:
                print("No new failures found.")
        except Exception as e:
            print(f"Connection error: {e} — retrying in 60s")
        print("Waiting 60 seconds...\n")
        time.sleep(60)

if __name__ == "__main__":
    watch()