import requests
import random
from datetime import datetime
import sys
import os

sys.path.append(os.path.dirname(os.path.abspath(__file__)))
from opero_runner import analyze_issue


PROJECT_ID = "gitlab-ai-hackathon%2Fparticipants%2F6273024"
TOKEN = "glpat-1oB42kUUpwfr8KM9NpQim286MQp1OjNxZ2FvCw.01.121g3pdrs"

errors = [
    "Database connection timeout",
    "Authentication failure",
    "503 Service Unavailable"
]

def create_issue(title, description):
    url = f"https://gitlab.com/api/v4/projects/{PROJECT_ID}/issues"
    headers = {"PRIVATE-TOKEN": TOKEN}
    data = {"title": title, "description": description}
    response = requests.post(url, headers=headers, data=data)
    print("Issue created:", response.status_code)
    print("Response:", response.text)
    return response

def comment_on_mr(mr_iid, analysis):
    url = f"https://gitlab.com/api/v4/projects/{PROJECT_ID}/merge_requests/{mr_iid}/notes"
    headers = {"PRIVATE-TOKEN": TOKEN}
    body = f"""## OPERO Risk Analysis

**Failure type:** {analysis['failure']}
**Severity:** {analysis['severity']}
**Suggested fix:** {analysis['fix'][0] if analysis['fix'] else 'Investigate logs'}

> Auto-generated by OPERO incident triage agent
"""
    data = {"body": body}
    response = requests.post(url, headers=headers, data=data)
    print("MR comment posted:", response.status_code)

def simulate_mr_review():
    # Simulates OPERO reviewing an open MR
    error = random.choice(errors)
    result = analyze_issue(error)
    comment_on_mr(1, result)  # MR iid=1, change as needed

def generate_rca(error, result):
    url = f"https://gitlab.com/api/v4/projects/{PROJECT_ID}/wikis"
    headers = {"PRIVATE-TOKEN": TOKEN}
    
    rca_content = f"""# RCA Report — {datetime.now().strftime('%Y-%m-%d %H:%M')}

## Incident Summary
- **Error:** {error}
- **Service:** Login API
- **Environment:** Production
- **Detected at:** {datetime.now()}

## Root Cause Analysis
- **Failure type:** {result['failure']}
- **Severity:** {result['severity']}

## Timeline
- {datetime.now()} — OPERO detected anomaly
- {datetime.now()} — Auto-triage completed
- {datetime.now()} — Issue created, team notified

## Resolution Steps
{chr(10).join(f'- {step}' for step in result['fix'])}

## Prevention
- Add monitoring alerts for this failure type
- Review runbook for {result['failure']}

> Auto-generated by OPERO
"""
    data = {
        "title": f"RCA-{datetime.now().strftime('%Y%m%d-%H%M')}",
        "content": rca_content,
        "format": "markdown"
    }
    response = requests.post(url, headers=headers, json=data)
    print("RCA report created:", response.status_code)

def simulate_monitor():
    if random.choice([True, False]):
        error = random.choice(errors)
        print(f"Detected error: {error}")

        result = analyze_issue(error)

        description = f"""
## OPERO Auto-Detected Incident

**Error:** {error}
**Service:** Login API
**Time:** {datetime.now()}
**Environment:** Production

## OPERO Pre-Analysis
- **Failure type:** {result['failure']}
- **Severity:** {result['severity']}
- **Suggested fix:** {result['fix'][0] if result['fix'] else 'Investigate logs'}
"""
        create_issue("OPERO Incident Detected", description)
        generate_rca(error, result)                           # Part 3
        print("Full OPERO triage complete!")
    else:
        print("System healthy - no incident detected")

if __name__ == "__main__":
    simulate_monitor()